### PR TITLE
bump to node16

### PR DESCRIPTION
**Pull request by benjimac93**
Bumps the action to use node16 rather than node12 as per: [GitHub Depreciation Notice](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) 

Tests are passing locally using node v16.13.1 + ubuntu latest has node v16.17.1

### CODE REVIEW

**Review by jbristowe — APPROVED** [review]

**Comment by jbristowe** [comment]
Closing due to old fork

**Comment by benjimac93** [comment]
@jbristowe would you like me to resubmit with an up to date fork ? or you going to handle on your end ?

**Comment by benjimac93** [comment]
I'm up to date with main too ?

**Comment by domenicsim1** [comment]
Hi @benjimac93, sorry for the confusion. 
You are update. 
The problem seems to be our workflows are not working with your PR so the tests are not running blocking us from merging the PR. I will be making a fix for this shortly.

**Comment by benjimac93** [comment]
@domenicsim1 is there anything you need from me to push this forward?

**Pull request merged**
